[settings]
experimental = true
python.uv_venv_auto = true

[env]
COVERAGE_RCFILE = "configs/.coveragerc"
TB_RUFF_VERSION = "0.12.10"
TB_ADD_TRAILING_COMMA_VERSION = "3.2.0"

[tools]
uv = "0.7.20"
taplo = "0.10.0"
node = "24.4.1"
pnpm = "10.13.1"
mdbook = "0.4.52"
yq = "4.47.1"
starship = "1.23.0"
